### ISSUE TITLE
metrics: do not mutate context when adding tags

### ISSUE THREAD

**Issue by nmiyake** [palantir/pkg#151]
Currently, there are scenarios in which `metrics.AddTags` mutates the contents of the provided context: https://github.com/palantir/pkg/blob/master/metrics/context.go#L49

This behavior is documented, but is unintuitive/quite different from the usual pattern, which generally treats contexts as immutable and makes a copy of the entire context before updating state.

I'm generally fine with changing this, but just want to take a look at the Git history of the original change, as I believe that I chose this behavior based on requests from clients/users. However, if this is not the case (or if the clients can agree to migrate to the new behavior), then I'm all for changing this.

**Comment by MatthewMaclean** [comment]
Yeah, generally a fan that when a function mutates an object that it should not return it. I know it makes it more cumbersome to use at times, but definitely communicates intent via the signature better.

Would definitely prefer it returns a new context though.

**Comment by MatthewMaclean** [comment]
I would prefer it moves to being immutable, but if we do keep it as mutable could we have it not return anything? I find that usually communicates the mutation guarantees of the function better, though it is more cumbersome to use.
